### ISSUE TITLE
RS3

### ISSUE THREAD

**Issue by Menomenta** [maxswa/osrs-json-hiscores#11]
First of all, thank your for this great package!
Have you considered making one for RS3 as well?

**Comment by maxswa** [comment]
It shouldn't be too hard to add support for RS3, the api is very similar. I would consider just adding it to this package since a lot of the logic will overlap.

**Comment by Menomenta** [comment]
That would be much appreciated!

**Comment by maxswa** [comment]
Don't have a lot of free time to work on this, I might come back to it at a later date.
