### ISSUE TITLE
CheerioElement

### ISSUE THREAD

**Issue by sembinner** [maxswa/osrs-json-hiscores#12]
I get this error when importing.

![image](https://user-images.githubusercontent.com/22047061/83245868-a21f7a80-a1a1-11ea-88e0-64693b578229.png)

**Comment by maxswa** [comment]
I'll try and reproduce this over the weekend.

**Comment by maxswa** [comment]
Sorry for the delay, this should be fixed now with this release: https://github.com/maxswa/osrs-json-hiscores/releases/tag/v2.2.0
