### ISSUE TITLE
Boss hiscores incorrectly mapped after introduction of Soul Wars Zeal

### ISSUE THREAD

**Issue by molo-pl** [maxswa/osrs-json-hiscores#19]
The data pulled from https://secure.runescape.com/m=hiscore_oldschool?player= now contains an additional entry for "Soul Wars Zeal", right after "LMS", before "Abyssal Sire". This breaks the mapping of rank & score of bosses, shifting them by one (so rank & score of Abyssal Sire is interpreted as rank & score of Alchemical Hydra, and so on).

**Comment by JTempdog** [comment]
Yes I just ran into this problem myself and thought it was on my end... Any idea how long this will take to be fixed? I'm trying to decide whether or not I should just change my code to use incorrect bosses to get the right output. Thank you.

**Comment by molo-pl** [comment]
> Any idea how long this will take to be fixed?

@JTempdog I've already opened pull request #20 with a fix. Now it's just a matter of it being reviewed by @maxswa.

> I'm trying to decide whether or not I should just change my code to use incorrect bosses to get the right output.

If you'd like to hotfix it locally, as a bare minimum only need to apply changes from the aforementioned PR from `src/hiscores.ts` line `268` to skip a row after LMS. (Make sure your `lib/hiscores.js` contains the change too.)

**Comment by maxswa** [comment]
I apologize, I am just seeing this now. Thank you for opening this issue and PR! I will be merging and publishing a new version in the next few minutes.

**Comment by maxswa** [comment]
Published as `osrs-json-hiscores@2.3.0` https://github.com/maxswa/osrs-json-hiscores/releases/tag/v2.3.0
