### ISSUE TITLE
Error on `npm start` after requiring

### ISSUE THREAD

**Issue by kyleshepherd** [maxswa/osrs-json-hiscores#24]
Hi, I'm trying to use this in a project, but once I require the package, I get this error on running `npm start`

```ModuleNotFoundError: Module not found: Error: Can't resolve 'canvas' in '/Users/kyle/repos/osrs-api/node_modules/jsdom/lib/jsdom'```

I'm not sure why just adding `const hiscores = require("osrs-json-hiscores");` causes this, hopefully you can shed some light!

**Comment by maxswa** [comment]
I've never encountered this issue before. It looks like some other people have though when using jsdom: https://github.com/jsdom/jsdom/issues/3042
If that doesn't solve the issue, let me know. I can try and investigate further.
