### ISSUE TITLE
Bounty Hunter types are flipped the wrong way.

### ISSUE THREAD

**Issue by Not-Jayden** [maxswa/osrs-json-hiscores#25]
Hey @maxswa , been using your API for a Twitch bot I'm working on. Super cool. I noted the Bounty Hunter stats are wrong however. 99% sure it's due to the order here not matching the order in the hiscores. would have commited the change myself but I can't seem to be able to make branches.

https://github.com/maxswa/osrs-json-hiscores/blob/2f788fabf61d894d23014286ef44c6a11a0aa790/src/utils/constants.ts#L62

Should be this I believe:
`export const BH_MODES: BHType[] = ['hunter', 'rogue'];`

**Comment by maxswa** [comment]
Thanks for reporting this bug! This must have been changed at some point without warning. The struggles of using an unofficial API... I can make this change and publish a new version today.

In the future, if you want to contribute to an open source repo you need to fork it, make changes on your fork, then make a PR. Here's some documentation on making a PR from a fork [creating-a-pull-request-from-a-fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by Not-Jayden** [comment]
Awesome thanks appreciate it! I knew there should be a way to do it I just don't contribute to open source enough 😬
