### ISSUE TITLE
Cannot get stats on user names with dashes in them

### ISSUE THREAD

**Issue by jerome3o** [maxswa/osrs-json-hiscores#28]
Minimum reproducible example:
```
const hiscores = require('osrs-json-hiscores');
hiscores
    .getStats('jerome-o')
    .then(res => {console.log(res);})
    .catch(err => console.error(err));\
```

**Comment by jerome3o** [comment]
this is the diff:
```
diff --git a/src/hiscores.ts b/src/hiscores.ts
index a680faf..a459ef4 100644
--- a/src/hiscores.ts
+++ b/src/hiscores.ts
@@ -39,7 +39,7 @@ import {
 export async function getRSNFormat(rsn: string): Promise<string> {
   if (typeof rsn !== 'string') {
     throw Error('RSN must be a string');
-  } else if (!/^[a-zA-Z0-9 _]+$/.test(rsn)) {
+  } else if (!/^[a-zA-Z0-9 _\-]+$/.test(rsn)) {
     throw Error('RSN contains invalid character');
   } else if (rsn.length > 12 || rsn.length < 1) {
     throw Error('RSN must be between 1 and 12 characters');
```

**Comment by jerome3o** [comment]
I couldn't push :(

**Comment by maxswa** [comment]
Thanks for reporting this bug, I've published a new version of the package `osrs-json-hiscores@2.4.1` which contains this fix.

In the future, if you want to contribute to an open source repo you need to fork it, make changes on your fork, then make a PR. Here's some documentation on making a PR from a fork [creating-a-pull-request-from-a-fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by jerome3o** [comment]
Awesome yeah I'm pretty new to open source dev, thanks for the heads up, and thanks for the fix
