### ISSUE TITLE
[Bug] Boss results not returning correctly for `seasonal` gamemode

### ISSUE THREAD

**Issue by Not-Jayden** [maxswa/osrs-json-hiscores#34]
When calling `hiscores.getStatsByGamemode()` with `seasonal` as the gamemode, the results become offset at some point.

I believe it might be due to Tempoross not being added to the API result for the last leagues season, but I'm not entirely sure.

If you look at a [main hiscores](https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws?player=mofoe) API result vs the [seasonal hiscores](https://secure.runescape.com/m=hiscore_oldschool_seasonal/index_lite.ws?player=mofoe), you'll see there is one additional entry when comparing them.

And if you call `hiscores.getStatsByGamemode('mofoe', 'seasonal')` for that player, you'll notice that what should be the result for zulrah is instead under zulcano.

**Comment by Not-Jayden** [comment]
Fix for your review https://github.com/maxswa/osrs-json-hiscores/pull/35

**Comment by maxswa** [comment]
Fixed and published as `osrs-json-hiscores@2.5.1`

https://github.com/maxswa/osrs-json-hiscores/releases/tag/v2.5.1

Thanks again for your contribution!
