### ISSUE TITLE
New Boss: Phosani's Nightmare

### ISSUE THREAD

**Issue by Not-Jayden** [maxswa/osrs-json-hiscores#40]
New boss has been added so I assume the API is broken again. Posting for visibility, will get a PR up shortly.

**Comment by Not-Jayden** [comment]
https://github.com/maxswa/osrs-json-hiscores/pull/41

**Comment by maxswa** [comment]
A new version of the library has been published containing the new boss: `osrs-json-hiscores@2.6.0`

https://github.com/maxswa/osrs-json-hiscores/releases/tag/v2.6.0
