### ISSUE TITLE
getRSNFormat doesn't seem to actually return the display name

### ISSUE THREAD

**Issue by evanw555** [maxswa/osrs-json-hiscores#60]
Correct me if I'm wrong, but the purpose of `getRSNFormat` is to scrape the hiscores page for a given player and parse out their actual cased display name. When I try using this function in my project, it always seems to return the same casing used as the input RSN.

When looking deeper into this, it looks like you're scraping the individual player's hiscores page. If you actually look at a player's hiscores page, it'll render with the same casing you provide it.

Looking around the hiscores site, it looks like the only way to find the "true" display name of a player is to search by rank, then return the player's display name from the table at the corresponding rank.

Am I understanding what's going on here, or am I mistaken? If my understanding is correct, is there any chance this can be fixed?

**Comment by maxswa** [comment]
Thanks for looking into this! It actually is returning the formatted name, you can verify this for yourself using this URL:
https://secure.runescape.com/m=hiscore_oldschool/overall.ws?table=0&user=lYnX%20tiTAn

The problem appears to be that they have changed the styling of the highlighted user in the table. Currently we are looking for red colored text, which is no longer the styling applied to the row.

```ts
const spans = dom.window.document.querySelectorAll(
  'span[style="color:#AA0022;"]'
);
```

Current HTML for highlighted row:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/13290954/207983317-9590dfa7-bb1f-4c2b-8a63-c89cc1bfa8ba.png">

I'll work on a fix for this now. Thanks again for finding this issue!

**Comment by evanw555** [comment]
@maxswa Oh, interesting... I made the incorrect assumption that this URL was pointing to the player's personal levels/bosses page (which frustratingly shows whatever casing you provide it), but it looks like yeah this is the hiscores list page and show the correct casing. Thanks for correcting me!

As far as the actual bug goes, that's one unfortunate consequence of resorting to scraping webpages, as the HTML/CSS itself becomes the API... I wonder if there's a more stable way to query the DOM? If I had to guess, maybe checking the element class. The ultimate foolproof way would be to collect usernames on the page from something like hrefs, then sanitize the RSNs and compare them against the sanitized input RSN (but that also is subject to change as well).

Anyway, thanks for addressing this! Lmk when the new version is out

**Comment by maxswa** [comment]
Yeah it definitely was an imperfect solution, but there was no other identifier to use at the time. Now with the new styling, we should be able to use the `personal-hiscores__row personal-hiscores__row--type-highlight` class which will hopefully be more reliable.

You can actually see how it used to be here in the tests folder: [\_\_tests__/lynxTitanNamePage.html:467](https://github.com/maxswa/osrs-json-hiscores/blob/main/__tests__/lynxTitanNamePage.html#L467)
