### ISSUE TITLE
Error: Invalid hiscores format

### ISSUE THREAD

**Issue by APKiwi** [maxswa/osrs-json-hiscores#67]
Code has not changed, but has not been utilized in a while.

Could the highscores response from https://secure.runescape.com/m=hiscore_oldschool/index_lite.ws?player= have changed?

```
0|X  | 18/03 23:34: Error: Invalid hiscores format
0|X  | 18/03 23:34:     at parseStats (/home/nuc/X/node_modules/osrs-json-hiscores/lib/hiscores.js:109:15)
0|X  | 18/03 23:34:     at Object.<anonymous> (/home/nuc/X/node_modules/osrs-json-hiscores/lib/hiscores.js:215:35)
0|X  | 18/03 23:34:     at step (/home/nuc/X/node_modules/osrs-json-hiscores/lib/hiscores.js:44:23)
0|X  | 18/03 23:34:     at Object.next (/home/nuc/X/node_modules/osrs-json-hiscores/lib/hiscores.js:25:53)
0|X  | 18/03 23:34:     at fulfilled (/home/nuc/X/node_modules/osrs-json-hiscores/lib/hiscores.js:16:58)
0|X  | 18/03 23:34:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by maxswa** [comment]
Are you on the latest version of `osrs-json-hiscores`?

**Comment by APKiwi** [comment]
Thanks, looks like my solution was using 2.10

**Comment by maxswa** [comment]
Awesome, glad to hear that resolved your issue! Unfortunately Jagex doesn’t version their hiscores API and every time they add an item to the API response it is a breaking change 😅

**Comment by APKiwi** [comment]
Ridiculous, also they only supply raw data, surely it wouldn't hurt for some clarity of json/xml with headers!
