### ISSUE TITLE
Small issue with new bosses...

### ISSUE THREAD

**Issue by davidvorona** [maxswa/osrs-json-hiscores#72]
Hey @maxswa thanks for the really quick update, I had just finished my own branch adding in the 3 new bosses. It's not a show-stopper, but the blog post actually spelled Calvar'ion's name wrong (as Cal'varion).

Here's the wiki with the proper spelling: https://oldschool.runescape.wiki/w/Calvar%27ion

Again, thanks for getting on that update so quickly!

**Comment by maxswa** [comment]
Woah, that's really strange. It looks like the official OSRS hiscores has the wrong spelling:

[Hiscores page](https://secure.runescape.com/m=hiscore_oldschool/overall?category_type=1&table=20#headerHiscores):
![image](https://user-images.githubusercontent.com/13290954/231622311-9fc67243-c67d-44d6-bb2a-8fe45dbe8d44.png)

In game:
![image](https://user-images.githubusercontent.com/13290954/231624785-f79357be-fd2d-4776-92ad-f8db2d026939.png)

**Comment by maxswa** [comment]
Fixed with `osrs-json-hiscores@2.13.1`

**Comment by davidvorona** [comment]
Ha, classic HiScores jank...
