### ISSUE TITLE
Requests hanging indefinitely

### ISSUE THREAD

**Issue by evanw555** [maxswa/osrs-json-hiscores#74]
I recently updated my application to use `getStatsByGamemode` in a loop that blocks on each request. My application has occasionally been hanging for hours at a time with no error, and I'm thinking it's due to the underlying axios call. According to the [axios docs](https://github.com/axios/axios/blob/main/README.md#request-config), all requests have a default timeout of `0`, meaning that they'd hang forever.

Therefore, we should do one of the following in [this function](https://github.com/maxswa/osrs-json-hiscores/blob/main/src/utils/helpers.ts#L100):
1. Add a generous default timeout e.g. 30 seconds or 1 minute.
2. Somehow make this configurable, which would be a little more difficult since there are multiple static methods calling each other.

**Comment by maxswa** [comment]
Fixed with `osrs-json-hiscores@2.14.1`
