### ISSUE TITLE
Incomplete Regex in getStats, doesn't include hyphen

### ISSUE THREAD

**Issue by HappyGhetto** [maxswa/osrs-json-hiscores#79]
Line 63 of hiscores.js (this is from the node module, no typescript):

```js
else if (!/^[a-zA-Z0-9 _]+$/.test(rsn)) {
    throw Error('RSN contains invalid character');
}
```

Regex should be changed to allow hyphens, as they are allowed in RSNs

`[\-a-zA-Z0-9 _]`

**Comment by maxswa** [comment]
Looks like you are on a version older than `2.4.1`, as this was fixed in that version or newer.

**Comment by maxswa** [comment]
Here's the changes which added the hyphen:
- https://github.com/maxswa/osrs-json-hiscores/compare/v2.4.0...v2.4.1#diff-bdf9313d87dbed1a380f73514bcb48d4a9bcf1b27cbe5e381c651486f5e49badR42
- https://github.com/maxswa/osrs-json-hiscores/pull/29

**Comment by maxswa** [comment]
I'm going to close this issue for now, if you update to `2.4.1` or newer and are still experiencing issues I can reopen this.

**Comment by HappyGhetto** [comment]
You're right, very strange how I wasn't on latest. My bad.
