### ISSUE TITLE
JSON Endpoint

### ISSUE THREAD

**Issue by seditionist** [maxswa/osrs-json-hiscores#82]
Would it be possible to switch from the CSV endpoint to the JSON endpoint to prevent the INVALID_FORMAT_ERROR every time something new gets added to the hiscores?

Endpoint is available here:
https://secure.runescape.com/m=hiscore_oldschool/index_lite.json?player=

Some references in RuneLite's repo to help: 
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/hiscore/HiscoreEndpoint.java

**Comment by maxswa** [comment]
Woah, how long has this existed for OSRS?

**Comment by maxswa** [comment]
Looks like at least since February judging by the Runelite commit that introduced it: https://github.com/runelite/runelite/commit/70476ef554c10c2b8779c672e1d5e684fde12e8b#diff-a0ff7bf143613769aad3b08bd3ddf7b20576c5ebcdf40da6a12c1f7033853ba7R36

**Comment by maxswa** [comment]
If I had known about this earlier I would have switched to this long ago, it's just a shame that the `id`s don't appear to be unique, it looks like they behave more like and index which is kind of unhelpful.

**Comment by seditionist** [comment]
Happened to see it mentioned in the RL discord and immediately thought of how it could improve reliability of this package.  Maybe worth having two separate functions; one that throws if outdated and one that always parses known stats?

I personally would love for my apps to be able to still fetch data after an update.  Although I can understand the use case of not wanting incomplete data.

**Comment by davidvorona** [comment]
Woah, this is awesome.

**Comment by maxswa** [comment]
The JSON endpoint is now being used in `osrs-json-hiscores@2.16.0`! :tada:
