### ISSUE TITLE
Misleading README regarding official hiscores API

### ISSUE THREAD

**Issue by clairemira** [maxswa/osrs-json-hiscores#92]
The official RuneScape Hiscores API does actually provide an endpoint returning a JSON response, however the README states that it only returns CSV. I'm assuming that only the CSV endpoint was available at the time the README was written, as I can see the code does indeed reference the official JSON endpoint. I think due to the fact an endpoint does now exist from the official API, that the README should get updated to reflect that to avoid throwing people off like it did for me.

**Comment by maxswa** [comment]
Good point, I will definitely update the README. This package has actually been updated to use the new JSON endpoint as well, so it's doubly misleading. 😅 Sorry about that!

**Comment by clairemira** [comment]
> Good point, I will definitely update the README. This package has actually been updated to use the new JSON endpoint as you said, so it's doubly misleading. 😅 Sorry about that!

Hey it's no worries :) it's an awesome project you have here. I would have submitted a PR but I'm not sure on the wording 😅.
